const allDataProduct =  [
        {
            _id: '1',
            name: 'Korean Sweater',
            category: 'Sweater',
            image: '/sweater/product1.jpg',
            price: 60,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Korean Sweater',
            category: 'Sweater',
            image: '/sweater/product2.jpg',
            price: 60,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Korean Sweater',
            category: 'Sweater',
            image: '/sweater/product3.jpg',
            price: 60,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Korean Sweater',
            category: 'Sweater',
            image: '/sweater/product4.jpg',
            price: 60,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Korean Sweater',
            category: 'Sweater',
            image: '/sweater/product5.jpg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Korean Sweater',
            category: 'Sweater',
            image: '/sweater/product6.jpg',
            price: 60,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '7',
            name: 'Korean Sweater',
            category: 'Sweater',
            image: '/sweater/product7.jpg',
            price: 60,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '8',
            name: 'Korean Sweater',
            category: 'Sweater',
            image: '/sweater/product8.jpg',
            price: 60,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '9',
            name: 'Airsim T-Shirt',
            category: 'tshirt',
            image: '/tshirt/tshirt1.avif',
            price: 30,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '10',
            name: 'Korean Sweater',
            category: 'tshirt',
            image: '/tshirt/tshirt2.avif',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '11',
            name: 'Korean Sweater',
            category: 'tshir',
            image: '/tshirt/tshirt3.avif',
            price: 25,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '12',
            name: 'Korean Sweater',
            category: 'tshirt',
            image: '/tshirt/tshirt4.avif',
            price: 55,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ]

