const allDataProduct =  [
        {
            id: '1',
            name: 'Korean Sweater',
            category: 'sweater',
            image: 'sweater/product1.jpg',
            price: 60,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '2',
            name: 'Korean Sweater',
            category: 'sweater',
            image: 'sweater/product2.jpg',
            price: 60,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '3',
            name: 'Korean Sweater',
            category: 'sweater',
            image: 'sweater/product3.jpg',
            price: 60,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '4',
            name: 'Korean Sweater',
            category: 'sweater',
            image: 'sweater/product4.jpg',
            price: 60,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '5',
            name: 'Korean Sweater',
            category: 'sweater',
            image: 'sweater/product5.jpg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '6',
            name: 'Korean Sweater',
            category: 'sweater',
            image: 'sweater/product6.jpg',
            price: 60,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '7',
            name: 'Korean Sweater',
            category: 'sweater',
            image: 'sweater/product7.jpg',
            price: 60,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '8',
            name: 'Korean Sweater',
            category: 'sweater',
            image: 'sweater/product8.jpg',
            price: 60,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '9',
            name: 'Airsim T-Shirt',
            category: 'tshirt',
            image: 'tshirt/tshirt1.avif',
            price: 30,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '10',
            name: 'Korean Sweater',
            category: 'tshirt',
            image: 'tshirt/tshirt2.avif',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '11',
            name: 'Korean Sweater',
            category: 'tshir',
            image: 'tshirt/tshirt3.avif',
            price: 25,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '12',
            name: 'Korean Sweater',
            category: 'tshirt',
            image: 'tshirt/tshirt4.avif',
            price: 55,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '13',
            name: 'Korean Pants',
            category: 'pants',
            image: 'pants/pants1.png',
            price: 55,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '14',
            name: 'Korean Pants',
            category: 'pants',
            image: 'pants/pants2.png',
            price: 55,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '15',
            name: 'Korean Pants',
            category: 'pants',
            image: 'pants/pants3.png',
            price: 55,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '16',
            name: 'Korean Pants',
            category: 'short',
            image: 'short/short1.png',
            price: 60,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '17',
            name: 'Korean Pants',
            category: 'short',
            image: 'short/short2.png',
            price: 30,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '18',
            name: 'Korean Pants',
            category: 'short',
            image: 'short/short3.png',
            price: 60,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '19',
            name: 'Korean Pants',
            category: 'short',
            image: 'short/short4.png',
            price: 60,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '20',
            name: 'Korean Pants',
            category: 'cap',
            image: 'cap/cap1.jpg',
            price: 30,
            brand: 'Shein',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '21',
            name: 'Korean Pants',
            category: 'cap',
            image: 'cap/cap2.jpg',
            price: 60,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            id: '22',
            name: 'Korean Pants',
            category: 'cap',
            image: 'cap/cap3.jpg',
            price: 60,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        }
    ]
